[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8502
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
